package Vista;

import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author Manuel Espinosa Torres
 */
public class FinestraPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FinestraPrincipal
     */
    public FinestraPrincipal() {
        initComponents();

        super.setTitle("Pràctica 5B");
        isWindowThrown = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionJMenu = new javax.swing.JMenu();
        formUpdateJMenuItem = new javax.swing.JMenuItem();
        directUpdateJMenuItem = new javax.swing.JMenuItem();
        fullUpdateJMenuItem = new javax.swing.JMenuItem();
        exitJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        optionJMenu.setText("Opcions");

        formUpdateJMenuItem.setText("Actualització per formulari");
        formUpdateJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formUpdateJMenuItemActionPerformed(evt);
            }
        });
        optionJMenu.add(formUpdateJMenuItem);

        directUpdateJMenuItem.setText("Actualització directa");
        directUpdateJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directUpdateJMenuItemActionPerformed(evt);
            }
        });
        optionJMenu.add(directUpdateJMenuItem);

        fullUpdateJMenuItem.setText("Actualització completa");
        fullUpdateJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullUpdateJMenuItemActionPerformed(evt);
            }
        });
        optionJMenu.add(fullUpdateJMenuItem);

        exitJMenuItem.setText("Eixir");
        exitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJMenuItemActionPerformed(evt);
            }
        });
        optionJMenu.add(exitJMenuItem);

        jMenuBar1.add(optionJMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formUpdateJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formUpdateJMenuItemActionPerformed
        if (!isWindowThrown) {
            JInternalFrame1 clientJFrame1 = new JInternalFrame1();
            clientJFrame1.setTitle("Actualització per formulari");
            clientJFrame1.addInternalFrameListener(new InternalFrameAdapter() {
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    isWindowThrown = false;
                }

            });
            jDesktopPane1.add(clientJFrame1);

            isWindowThrown = true;
        } else {
            showInfoDialog();
        }
    }//GEN-LAST:event_formUpdateJMenuItemActionPerformed

    private void directUpdateJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directUpdateJMenuItemActionPerformed
        if (!isWindowThrown) {
            JInternalFrame2 clientJFrame2 = new JInternalFrame2();
            clientJFrame2.setTitle("Actualització directa");
            clientJFrame2.addInternalFrameListener(new InternalFrameAdapter() {
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    isWindowThrown = false;
                }

            });
            jDesktopPane1.add(clientJFrame2);

            isWindowThrown = true;
        } else {
            showInfoDialog();
        }
    }//GEN-LAST:event_directUpdateJMenuItemActionPerformed

    private void fullUpdateJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullUpdateJMenuItemActionPerformed
        if (!isWindowThrown) {
            JInternalFrame3 clientJFrame3 = new JInternalFrame3();
            clientJFrame3.setTitle("Actualització completa");
            clientJFrame3.addInternalFrameListener(new InternalFrameAdapter() {
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    isWindowThrown = false;
                }

            });
            jDesktopPane1.add(clientJFrame3);

            isWindowThrown = true;
        } else {
            showInfoDialog();
        }
    }//GEN-LAST:event_fullUpdateJMenuItemActionPerformed

    private void exitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitJMenuItemActionPerformed

    public void showInfoDialog() {
        JOptionPane.showMessageDialog(this,
                "No pots obrir una opció si ja roman oberta altra.", "Informació",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FinestraPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem directUpdateJMenuItem;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JMenuItem formUpdateJMenuItem;
    private javax.swing.JMenuItem fullUpdateJMenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu optionJMenu;
    // End of variables declaration//GEN-END:variables
    private boolean isWindowThrown;
}
